[theme]

# Learn more at: https://blog.streamlit.io/introducing-theming/

# Primary accent for interactive elements
primaryColor = '#6c43bd'

# Background color for the main content area
backgroundColor="#ffffff"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#f1efed"

# Color used for almost all text
textColor = '#242424'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
